---
  name: "komi-frontend"
  version: "1.0.0"
  scripts: 
    dev: "vite"
    build: "vite build"
    preview: "vite preview"
  dependencies: 
    @tanstack/react-query: "^5.51.0"
    clsx: "^2.1.1"
    react: "^18.3.1"
    react-dom: "^18.3.1"
  devDependencies: 
    @types/node: "^22.7.4"
    @types/react: "^18.3.10"
    @types/react-dom: "^18.3.0"
    @vitejs/plugin-react: "^4.2.1"
    typescript: "^5.6.2"
    vite: "^5.4.7"

